import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";

export default function Home() {
  const [tweets, setTweeets] = useState([])
  const [stock_name, setstock_name] = useState("AAPL");

  const nowDate = new Date();
  const todayDate = nowDate.getDate();

  const formatYmd = (date) => date.toISOString().slice(0, 10);

  async function getTweets(stock){
    const alltweets = [];
    for (let i = 0; i < 2; i++){
      const res = await fetch(`https://scrapybook.axemgit2.repl.co/twitter?stock=${stock}&since=2022-01-${todayDate-i}&until=2022-01-${(todayDate+1)-i}`);
      const json = await res.json();
      alltweets = alltweets.concat(json);
    }
    for (const value of Object.entries(alltweets)) {
      const date = new Date(value[1].Datetime);
      value[1].Datetime = formatYmd(date);
    }
    console.log(alltweets)
    setTweeets(alltweets);
  }

  function shake_shake(arr) {
    const dateTweets = arr.reduce(function(results, item) {
      if (!results[item.Datetime]) results[item.Datetime] = [];
      results[ item.Datetime ].push(item.Text);
      
      return results;
    }, {});
    // return dateTweets
    return Object.keys(dateTweets).map(function(key) {
      return { date: key, news: dateTweets[key] };
    });
  }
  const result = shake_shake(tweets);
  console.log(result);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Invisor!</a>
        </h1>
        <button onClick={() => getTweets(stock_name)}>Click Me</button>
        <p className={styles.description}>
          Tweets are: 
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://asimali.net"
          target="_blank"
          rel="noopener noreferrer"
        >
          Crafted By Asim Ali
        </a>
      </footer>
    </div>
  )
}
